default_agent: specagent
agents:
  specagent:
    name: specagent
    entrypoint: /Users/jeon-yeongho/Documents/project/airdevops-mcp/agentcore-spec/spec_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/jeon-yeongho/Documents/project/airdevops-mcp/agentcore-spec
    aws:
      execution_role: arn:aws:iam::658886689642:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-9ab9dc1e3f
      execution_role_auto_create: false
      account: '658886689642'
      region: ap-northeast-1
      ecr_repository: 658886689642.dkr.ecr.ap-northeast-1.amazonaws.com/bedrock-agentcore-specagent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: specagent-Xl9a5QHYbF
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:658886689642:runtime/specagent-Xl9a5QHYbF
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-specagent-builder
      execution_role: arn:aws:iam::658886689642:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-northeast-1-9ab9dc1e3f
      source_bucket: bedrock-agentcore-codebuild-sources-658886689642-ap-northeast-1
    memory:
      mode: STM_ONLY
      memory_id: specagent_mem-ONRrFBEq8q
      memory_arn: arn:aws:bedrock-agentcore:ap-northeast-1:658886689642:memory/specagent_mem-ONRrFBEq8q
      memory_name: specagent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
